name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc2fb9d1a8a1f93b072b54f4aae52a763c7a28e3203140f82661b5bbf476d97e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
