name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29b0a0eef2b8152be854316d9a25ba5d4a89139685f0d4aebc9190901c835aa5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
